name: Extract ZIP file

on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Unzip file
        run: |
          sudo apt-get install unzip
          unzip VirtualZoo_Assignment_COMP8702.zip -d extracted_files

      - name: Commit unzipped files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add extracted_files
          git commit -m "Unzipped VirtualZoo_Assignment_COMP8702.zip"
          git push
